# Generated by Django 4.2.4 on 2024-07-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='saved_ideas',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='favorited_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ideas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='news',
        ),
        migrations.RemoveField(
            model_name='project',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
