# Generated by Django 4.2.4 on 2024-01-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='favorited_by',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
